services:
  rf-fe:
    container_name: rf-fe-container
    build:
      context: ./RF_FE # Path to your frontend Dockerfile directory
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map container port 3000 to host port 3000
    networks:
      - app-network
    depends_on:
      - rf-be # Wait for rf-be service to be ready before starting rf-fe
    command: ["npm", "run", "dev"]

  rf-be:
    container_name: rf-be-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1010:1010" # Map container port 5000 to host port 5000
    networks:
      - app-network
    environment:
      - NODE_ENV=development
